### ISSUE TITLE
Migrar a postgres

### ISSUE THREAD

**Issue by jerivas** [hopechan/django-blog#3]
Actualmente estamos usando sqlite (y toda la base de datos se encuentra en git). Por favor cambia el proyecto para utilizar una base de datos postgres. Aquí algunos pasos:

- Elimina el archivo sqlite del repositorio
- Crea una base de datos en postgres y un usuario que tenga permisos para acceder a ella. Guarda los datos de la conexión
- Configura `settings.py` para utlizar postgres en lugar de sqlite, llenando la configuración con los datos del paso anterior. Aquí un link de ejemplo https://www.digitalocean.com/community/tutorials/how-to-use-postgresql-with-your-django-application-on-ubuntu-14-04#configure-the-django-database-settings
- Genera migraciones para la app "polls" e incluyelas en el repo

Ojo, que esto hará que empieces con una base de datos desde cero. No es necesario que el contenido del sitio (base de datos) esté en control de versión.

**Comment by hopechan** [comment]
Hola, ya esta hecha la migración a postgres
